---
dependencies:
  meta: ">=1.16.0 <2.0.0"
description: "'A pure Dart implementation of Canvas API compatible with dart:ui.'"
dev_dependencies:
  test: any
environment:
  sdk: ^3.2.0
homepage: https://github.com/normidar/pure_ui
name: pure_ui
topics:
  - image
  - dart-ui
  - canvas
  - pure-dart
  - ui
version: 0.1.0
