---
dependencies:
  image: ^4.0.0
  meta: ">=1.16.0 <2.0.0"
description: "'A pure Dart implementation of Canvas API compatible with dart:ui.'"
dev_dependencies:
  auto_exporter: any
  build_runner: any
  test: any
environment:
  sdk: ^3.2.0
name: pure_ui
repository: https://github.com/normidar/pure_ui
version: 0.0.2
